## Using https://github.com/arnp/herring-cove theme
#
name: Unité de Transplantation Hépatique
author: Jean-Baptiste Richardet
baseurl: /ARPHD
description: Hôpital Henri Mondor Créteil, France
email: contact[at]aphp.fr

##Make sure to edit the above fields, especially for disqus.


#highlighter: pygments
#markdown: redcarpet
#redcarpet:
#  extensions: ["tables"]

markdown: kramdown

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

destination: docs
exclude: ["script", "Gemfile"]

gems:
  - jekyll-sitemap
